-- USERS
CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  full_name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  balance NUMERIC(12,2) DEFAULT 0 NOT NULL,
  created_at TIMESTAMP DEFAULT NOW()
);

-- TRANSACTIONS (histórico de créditos)
CREATE TABLE IF NOT EXISTS transactions (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id),
  amount NUMERIC(12,2) NOT NULL,
  created_at TIMESTAMP DEFAULT NOW()
);

-- BETS
CREATE TABLE IF NOT EXISTS bets (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id),
  numbers TEXT NOT NULL,
  contest INTEGER NOT NULL,
  cost NUMERIC(12,2) NOT NULL,
  repeats INTEGER DEFAULT 1 NOT NULL,
  paid BOOLEAN DEFAULT true NOT NULL,
  created_at TIMESTAMP DEFAULT NOW()
);
